### ISSUE TITLE
need SpeechRecognition input node

### ISSUE THREAD

**Issue by monteslu** [monteslu/pagenodes#40]
should look like the speech synthesis node, but as an input

can use `window.webkitSpeechRecognition` API if available.

**Comment by samrocksc** [comment]
Is this an addon espeak already in existence or a separate node?

**Comment by samrocksc** [comment]
Quick Rundown

* Color #ffb6c1
* Input wires: 1, Output Wires: 1
* Takes speech on request and interprets it delivering as an object/string.
* Has option for always on, or inject allowing to interpret a command?

Correct?

**Comment by monteslu** [comment]
nope, no input wire, just an output wire.  this should behave similar to the gamepad node.  It creates new messages

**Comment by samrocksc** [comment]
Okay, cool, so ditch the on tap-to-talk method?

**Comment by monteslu** [comment]
yeah.  Might eventually want a toggle to turn it off, but start off simple.

**Comment by samrocksc** [comment]
Resolved in #41
