### ISSUE TITLE
move client js into editor source

### ISSUE THREAD

**Issue by monteslu** [monteslu/pagenodes#5]
We currently have client javascript embedded into html files in the `nodes/` folder.

We need this code to be moved into `src/editor/nodeDefs/js/`

Each of these will need to be wrapped in a 
```javascript
module.exports = function(RED){
  ...client js cod
};
```

and then add to the `src/editor/nodeDefs/js/index.js`

First start off with `sentiment` `inject` and `debug` nodes.

**Comment by samrocksc** [comment]
This one is closed
