### ISSUE TITLE
Question: DId you use a library for your drag and drop query building?

### ISSUE THREAD

**Issue by paul42** [monteslu/pagenodes#62]
I'm a huge fan of the drag and drop query building - do you know off hand if there are any libraries that I can utilize in my other projects to get close to this functionality?

Thanks in advance,
Paul

**Comment by monteslu** [comment]
@paul42 this UI is based on node-red which uses jquery and D3.
It's tightly coupled to the rest of the codebase, so it might be a lot of work to try and re-use it.

D3 is pretty straight forward itself though.

**Comment by paul42** [comment]
Awesome, thanks for pointing me towards those libraries! your project looks really cool, I'm looking forward to tinkering 👍
